/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as ReponsesRouteImport } from './routes/reponses'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as LeadsIdRouteImport } from './routes/leads.$id'
import { Route as ApiPublicReceiveEmailWebhookRouteImport } from './routes/api/public/receive-email-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const ReponsesRoute = ReponsesRouteImport.update({
  id: '/reponses',
  path: '/reponses',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIdRoute = LeadsIdRouteImport.update({
  id: '/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReceiveEmailWebhookRoute =
  ApiPublicReceiveEmailWebhookRouteImport.update({
    id: '/api/public/receive-email-webhook',
    path: '/api/public/receive-email-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/radar': typeof RadarRoute
  '/reponses': typeof ReponsesRoute
  '/leads/$id': typeof LeadsIdRoute
  '/leads/': typeof LeadsIndexRoute
  '/api/public/receive-email-webhook': typeof ApiPublicReceiveEmailWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/radar': typeof RadarRoute
  '/reponses': typeof ReponsesRoute
  '/leads/$id': typeof LeadsIdRoute
  '/leads': typeof LeadsIndexRoute
  '/api/public/receive-email-webhook': typeof ApiPublicReceiveEmailWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/radar': typeof RadarRoute
  '/reponses': typeof ReponsesRoute
  '/leads/$id': typeof LeadsIdRoute
  '/leads/': typeof LeadsIndexRoute
  '/api/public/receive-email-webhook': typeof ApiPublicReceiveEmailWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/radar'
    | '/reponses'
    | '/leads/$id'
    | '/leads/'
    | '/api/public/receive-email-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/radar'
    | '/reponses'
    | '/leads/$id'
    | '/leads'
    | '/api/public/receive-email-webhook'
  id:
    | '__root__'
    | '/'
    | '/radar'
    | '/reponses'
    | '/leads/$id'
    | '/leads/'
    | '/api/public/receive-email-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RadarRoute: typeof RadarRoute
  ReponsesRoute: typeof ReponsesRoute
  LeadsIdRoute: typeof LeadsIdRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
  ApiPublicReceiveEmailWebhookRoute: typeof ApiPublicReceiveEmailWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reponses': {
      id: '/reponses'
      path: '/reponses'
      fullPath: '/reponses'
      preLoaderRoute: typeof ReponsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$id': {
      id: '/leads/$id'
      path: '/leads/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof LeadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/receive-email-webhook': {
      id: '/api/public/receive-email-webhook'
      path: '/api/public/receive-email-webhook'
      fullPath: '/api/public/receive-email-webhook'
      preLoaderRoute: typeof ApiPublicReceiveEmailWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RadarRoute: RadarRoute,
  ReponsesRoute: ReponsesRoute,
  LeadsIdRoute: LeadsIdRoute,
  LeadsIndexRoute: LeadsIndexRoute,
  ApiPublicReceiveEmailWebhookRoute: ApiPublicReceiveEmailWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
